### ISSUE TITLE
mobo --init results in error

### ISSUE THREAD

**Issue by magick93** [Fannon/mobo#15]
Hello

Im trying to get started and am having the following error when trying to create a project. Can you help?

OS: Ubuntu 15.10
node -v
v5.5.0

```
anton@anton-K93SV:~/workspaces/modeling/mobotest1$ mobo --init

/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:167
  throw generateError(state, message);
  ^
YAMLException: duplicated mapping key at line 217, column 27:
        specific: intermediary
                              ^
    at generateError (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:161:10)
    at throwError (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:167:9)
    at storeMappingPair (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:304:7)
    at readBlockMapping (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1064:9)
    at composeNode (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1055:11)
    at composeNode (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1055:11)
    at composeNode (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readDocument (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1490:3)
    at loadDocuments (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1546:5)
    at load (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1563:19)
    at Object.safeLoad (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1581:10)
    at Object.<anonymous> (/home/anton/local/lib/node_modules/mobo/lib/schema/moboSchema.js:29:40)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
anton@anton-K93SV:~/workspaces/modeling/mobotest1$ Y
```

I have tried removing the contents of /home/anton/local/lib/node_modules/ and re-installing. But the error continues to occur.

Thanks

**Comment by Fannon** [comment]
Hello @magick93 !

Thanks for reporting this!

This is a very unfortunate error, as it is introduced by breaking change of a 3rd party library (js-yaml). I've already fixed this in mobo v2 (devel branch). 

It might be a better idea to start with the 2x release anyway, as it introduces a lot of breaking changes but also a more consistent/flexible API/Framework. If you feel a bit adventerous, I'd recommend to try it instead. (It should be quite stable now).

In order to install it, check out the "devel" branch, and install all dependencies with npm install. Make the mobo command globally available though npm link.

https://www.gitbook.com/book/fannon/mobo2-documentation/details

Sorry, currently the projekt is in a big transitional phase.

Best,
Simon

**Comment by Fannon** [comment]
Ok, I hope I've fixed in in the v1 release of mobo

**Comment by magick93** [comment]
Hi Simon

Ok, I will try the devel branch. I'm not experienced with node, so it make take me sometime to install everything.

Thanks

**Comment by Fannon** [comment]
Ok! Theres one more issue with mobo v2. The documentation is still written for version 1, except the link above. So you'd have to do a lot of "transferring" - though its mostly just different names for the same thing.

If you want to just get started, it might be easier with mobo 1. If you want to really use it, it makes sense to go with version 2, as version 1 will deprecated soon

**Comment by magick93** [comment]
Yes, I would like to get started, and would prefer to do so on v1, as it seems most complete. However, due to the above error, am unable to.
I am getting the same error when I run 'mobo --update'.

**Comment by Fannon** [comment]
Did you try to reinstall mobo, since the last patch? (npm install -g mobo)

**Comment by magick93** [comment]
Yes, this is the result:

```
anton@anton-K93SV:~/workspaces/modeling/mobotest1$ npm install -g mobo
/home/anton/local/bin/mobo -> /home/anton/local/lib/node_modules/mobo/lib/cli.js
/home/anton/local/lib
└── mobo@1.8.2 

npm WARN optional Skipping failed optional dependency /mobo/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

And then the same error occurs if I try to create a project.

**Comment by Fannon** [comment]
This looks like just some warnings. NPM throws a lot of them, especially if
you're on windows. Does mobo itself work? With newer NPM versions there are
many bugs. Sometimes I have to install/update mobo twice so that NPM
fetches all dependencies correctly.

2016-01-25 12:10 GMT+01:00 magick93 <notifications@github.com>:

**Comment by magick93** [comment]
> Does mobo itself work?

No, I am still unable to get pass the original error. Unfortunately.

**Comment by magick93** [comment]
https://www.npmjs.com/package/fsevents - Native Access to Mac OS-X FSEvents
So, I think Mobo will only work on a mac.

**Comment by Fannon** [comment]
No, I'm using it on Windows / Linux, but not on a mac. As I said, NPM throws a lot of warning/error messages. This one is only an optional dependency that will only work on macs. If it's not working, an adequate fallback solution should be chosen

**Comment by magick93** [comment]
The problem seems to be to do with the /chokidar/fsevents depedency.

I deleted my node_modules directory, and tried to reinstall. But it fails with the same error.
```
anton@anton-K93SV:~/git/mobo$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

**Comment by Fannon** [comment]
What OS are you using?
What happens if you type "mobo -v" ?


2016-01-25 12:40 GMT+01:00 magick93 <notifications@github.com>:

**Comment by magick93** [comment]
OS: Ubuntu 15.10
node: v5.5.0
mobo:? when I try run the ``` mobo -v  ``` I get:

```
anton@anton-K93SV:~/git/mobo$ mobo -v

/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:167
  throw generateError(state, message);
  ^
YAMLException: duplicated mapping key at line 217, column 27:
        specific: intermediary
                              ^
    at generateError (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:161:10)
    at throwError (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:167:9)
    at storeMappingPair (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:304:7)
    at readBlockMapping (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1064:9)
    at composeNode (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1055:11)
    at composeNode (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1055:11)
    at composeNode (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readDocument (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1490:3)
    at loadDocuments (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1546:5)
    at load (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1563:19)
    at Object.safeLoad (/home/anton/local/lib/node_modules/mobo/node_modules/js-yaml/lib/js-yaml/loader.js:1581:10)
    at Object.<anonymous> (/home/anton/local/lib/node_modules/mobo/lib/schema/moboSchema.js:29:40)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
anton@anton-K93SV:~/git/mobo$ 
```

**Comment by Fannon** [comment]
Oh, sorry - I forgot to publish the last changes to the NPM Registry. If
you update now, it should be fixed.

(version 1.8.3)

2016-01-25 12:47 GMT+01:00 magick93 <notifications@github.com>:

**Comment by magick93** [comment]
Bingo!

Thanks Simon. 

Time to take mobo for a drive....
