### ISSUE TITLE
Help understanding error

### ISSUE THREAD

**Issue by magick93** [Fannon/mobo#16]
Hello

I am trying to get started with Mobo. I am trying to create a new project, but am basing it on the hardware project. Basically, I am trying have an Office form, and and office has a location.

I have the following location model (I have copied the fields from the hardware example):
```
title: Location
description: Location where office is located

items:
  - $extend: /field/streetAdress
  - $extend: /field/streetNumber
  - $extend: /field/town
  - $extend: /field/country

required:
  - streetAdress
  - streetNumber
  - town
```

And the following location form:
```
title: Location
description: This creates a new Office Location. 

items:
  - $extend: /model/Location


sf_forminfo:
  create title: Create a new location
  edit title: Edit a location
```

From my (limited) understanding, this should be enough and valid. However I am getting the following error:
```
Unhandled rejection TypeError: Cannot assign to read only property 'type' of title: Location
description: This creates a new Office Location.

items:
  - $extend: /model/Location


sf_forminfo:
  create title: Create a new location
  edit title: Edit a location

    at Object.exports.applyImplicit (/home/anton/local/lib/node_modules/mobo/lib/modelToModel/compatibilityLayer.js:256:22)
    at Object.exports.exec (/home/anton/local/lib/node_modules/mobo/lib/modelToModel/compatibilityLayer.js:50:21)
    at /home/anton/local/lib/node_modules/mobo/lib/mobo.js:109:43
    at tryCatcher (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/promise.js:676:18)
    at Async._drainQueue (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/anton/local/lib/node_modules/mobo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I am not sure what or where I have gone wrong. Can someone offer some guidance?

Note: I am working on a clean wiki. 

Thanks

**Comment by Fannon** [comment]
Hello!

I've never seen an error like this. Maybe this has something to do with linux permissions? Can you try running mobo with sudo?

**Comment by magick93** [comment]
Actually its working now. I had to stop and start mobo a few times. 

It seemed it was caching some files. For example, I would change the description and/or the title, but did not see this change in the error output. This is when I noticed the caching, and so exited Mobo. 

Now it seems fine, and I have my locations form published. 

I suggest we close this. If I find away to reproduce the issue I will update this.

Thanks

**Comment by Fannon** [comment]
Ok, thanks for reporting it! I haven't tested mobo much with Linux/Ubuntu.
I hope you won't run into further problems!

(I also think that mobo 2 could be more stable, should you decide to use it)

2016-01-27 14:37 GMT+01:00 magick93 <notifications@github.com>:
