### ISSUE TITLE
[E] [Graph] "template:<template name>" is malformed, missing its refenence, or ID!

### ISSUE THREAD

**Issue by cwillmes** [Fannon/mobo#19]
Hi,

I get some Errors, that I do not know how to debug. 
Since recently I get errors like this:

[11:20:38] [E] [Graph] "template:Dataset" is malformed, missing its refenence, or ID!
{
    "$extend": "/field/Temporal"
}
[11:20:38] [E] [Graph] "template:Dataset" is malformed, missing its refenence, or ID!
{
    "$extend": "/field/Spatial"
}
[11:20:38] [E] [Graph] "template:Dataset" is malformed, missing its refenence, or ID!
{
    "$extend": "/field/Topic"
}

For I think any /field/ definition in my model... 

Additionally I get the following Error message:

[11:22:31] Bot logging in with account: mobo
[11:22:31] --------------------------------------------------------------------------------
Unhandled rejection RangeError: Maximum call stack size exceeded
    at isArray (native)
    at baseClone (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:1697:19)
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:1734:23
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:3073:15
    at baseForOwn (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:2046:14)
    at baseClone (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:1733:39)
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:1734:23
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:3073:15
    at baseForOwn (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:2046:14)
    at baseClone (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:1733:39)
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:1734:23
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:3073:15
    at baseForOwn (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:2046:14)
    at baseClone (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:1733:39)
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:1734:23
    at /usr/lib/node_modules/mobo/node_modules/lodash/index.js:3073:15
    at baseForOwn (/usr/lib/node_modules/mobo/node_modules/lodash/index.js:2046:14)

  Any hints or advice on how to fix this? I do not know what change caused this...

**Comment by Fannon** [comment]
This is a very strange error. Can you disable the graph layer by adding this to your settings.yaml ?

buildGraph: false

**Comment by cwillmes** [comment]
adding 'buildGraph: false' to the settings changed the error messages to a "YAMLException", which led me see that the indentation was incorrect many files.
After fixing the indentations the error is gone.
I think its due to a different editor I used some days ago....
Thanks for the hint.
I close the issue now.
