### ISSUE TITLE
npm install error 'Call to 'node -e "require('nan')"' returned exit status 127'

### ISSUE THREAD

**Issue by gesinn-it** [Fannon/mobo#9]
`npm install` returns the following ERR with the latest version from git

gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/mobo/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok

**Comment by gesinn-it** [comment]
Okay, it seems that mobo needs at least node.js 0.12.x. Ubunutu 14.04 LTS comes with 0.10.x

Works now with node.js 0.12.7 installed via nvm.
